### ISSUE TITLE
Wrong version shown in Discord

### ISSUE THREAD

**Issue by jathek** [TakosThings/Fluent-Discord#107]
**Describe the bug**
Fluent Discord's version is listed as 1.0.0 in Discord despite using the v1.1.3/Fluent-Discord.theme.css file.

**Screenshots**
[The release file has 1.0.0 instead of 1.1.3.](https://github.com/TakosThings/Fluent-Discord/releases/download/v1.1.3/Fluent-Discord.theme.css)

**Comment by TakosThings** [comment]
This is intentional. The auto-updating file is only regenerated when changes are made to any of the below files.
```SCSS
// fluent-auto.scss
// [...]
@import 'modules/betterdiscord/meta';
@import 'modules/core/import';

@import 'modules/core/options';
```

The actual version number can be found at the bottom of the User Settings nav
![image](https://user-images.githubusercontent.com/20344790/161457232-01a08931-a865-42b4-9251-ed862dce5e9f.png)
