### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by distrair** [TakosThings/Fluent-Discord#134]
After i put the .css file in the themes folder, BD showed me an error:
![image](https://user-images.githubusercontent.com/78724291/173250436-aaa27ad9-f95a-49c8-ab6b-a68f9cd6591e.png)
How do i fox this?

**Comment by TakosThings** [comment]
Simplest solution would be to just try redownloading the theme from [releases](https://github.com/TakosThings/Fluent-Discord/releases/latest).

Though if you're building the theme yourself this usually happens when the SASS compiler throws an error. Check the console you run `npm run dev` from for an explanation
![image](https://user-images.githubusercontent.com/20344790/173321487-cef0c237-e967-4627-bfe9-c5fdffd52527.png)

Last resort: you'll have to check the console in developer tools which will give a more useful error message. For example: 
![image](https://user-images.githubusercontent.com/20344790/173321741-c3a2c0a7-547d-4fdd-8516-cb847dcef59a.png)
