### ISSUE TITLE
Add Powercord support

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#159]
**Is your feature request related to a problem? Please describe.**
It would be nice if this theme was compatible with Powercord from the get-go, and since you only have the BetterDiscord theme files, you'd have to convert them first.

**Describe the solution you'd like**
You should include Powercord theme files for this project alongside with the BetterDiscord ones.

**Additional context**
This is what I mean, using the convert here.
![image](https://user-images.githubusercontent.com/71488561/180611007-07a1bf92-6bb9-451a-aa6f-54d4b5190636.png)

**Comment by TakosThings** [comment]
Powercord devs have just ended the project, so I'm marking this as wontfix

**Comment by celunah** [comment]
> Powercord devs have just ended the project, so I'm marking this as wontfix

This is really sad.

**Comment by celunah** [comment]
> Powercord devs have just ended the project, so I'm marking this as wontfix

@TakosThings Update on this, Powercord has been [forked](https://github.com/replugged-org/replugged), so you now can unmark this `wontfix`, and add support for Replugged.

**Comment by PeterStrick** [comment]
> > Powercord devs have just ended the project, so I'm marking this as wontfix
> 
> @TakosThings Update on this, Powercord has been [forked](https://github.com/replugged-org/replugged), so you now can unmark this `wontfix`, and add support for Replugged.

@TakosThings It would be nice to add [Replugged](https://github.com/replugged-org/replugged) support, since it has been out of Beta now

Although the Theme Development is different between Replugged and Powercord now: https://guide.replugged.dev/docs/theme/getting-started

Cobbling a Replugged Theme together myself that just includes the Fluent Discord CSS works perfectly fine on Replugged
