### ISSUE TITLE
please support light mode

### ISSUE THREAD

**Issue by minotto165** [TakosThings/Fluent-Discord#270]
If you set it to light mode in discord's settings, the theme will appear to be disabled.
![image](https://github.com/TakosThings/Fluent-Discord/assets/109657703/fa666af9-2fd3-4eb4-bf2b-0c382404976b)
(Google Translate)

**Comment by yippii** [comment]
inside the .css file, it is clearly stated as .theme-dark, which made the theme only apply in dark mode.
this is intended because not everyone is using it and the theme itself is kinda only suitable for dark mode.
you can try to see if you can edit those codes to suit your need

### Tutorial from me (I am not dev)
Replace those .theme-dark with .theme-light
Try to fix those inconsistencies with the theme (may take 10+ hours)
Done :D

**Comment by TakosThings** [comment]
See #247. I'm not at all interested in working on a light mode option.
