### ISSUE TITLE
ThemeSettings

### ISSUE THREAD

**Issue by takymalycervik** [TakosThings/Fluent-Discord#36]
### Plugin Link

https://betterdiscord.app/plugin/ThemeSettings

### Notes

Please make some color settings for this plugin.

**Comment by TakosThings** [comment]
Are there any colour settings you're looking for in particular? Most of the colour in the theme is derived from your accent colour and the background you choose, otherwise almost all the UI is different shades of black and white.

You can check out the [variables](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/core/_variables.scss#L57-L212) file from line 57 down (everything above that is for reference/testing) to see what I mean.

**Comment by takymalycervik** [comment]
Some option for background colour when joined in voice/text channel, maybe some backround colour for messege where I´m tagged in
