### ISSUE TITLE
Acrylic/Mica window

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#47]
Is is possible to implement Acrylic or Mica that actually blurs what's behind it instead of just the blurring a preset background? Fluent design is great but the background is always off. It would be nice if it could be consistent with the rest of the system.

**Additional context**
If you see the Terminal app blurs what's behind it while Discord with Fluent-Discord theme just blurs its own background not the whole desktop.
![image](https://user-images.githubusercontent.com/43099141/156858968-d4c815b8-787e-44d7-9abe-de03f754e7ea.png)

**Comment by TakosThings** [comment]
Unfortunately no. Discord uses a different tech to UWP apps called Electron, which is essentially a stand alone Chrome browser. Electron has a bunch of issues with implementing acrylic/mica which I doubt will ever be resolved.

While there is an option to enable transparency in Discord, CSS can't apply filters to anything 'outside' of Discord. Window snapping and double clicking the title bar to maximise/minimise also breaks when the option is enabled which is why it's on the not supported list.

~~I have experimented with improving the 'acrylic' effect which would make it work a little better with complex backgrounds, so this change might make it into a future build some time.~~ This will be in the next release.

**Comment by christianavi** [comment]
>This will be in the next release.

Was this included on `v0.0.13`?

**Comment by RikisuT** [comment]
Will using https://github.com/arkenthera/electron-vibrancy or https://github.com/Seo-Rii/electron-acrylic-window help?
