### ISSUE TITLE
Option to decrease padding of some buttons

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#54]
There are buttons on the upper right side of the window which I think are too wide. Maybe the padding of these buttons could be added to a variable users could easily change any time.

**Additional context**
![image](https://user-images.githubusercontent.com/43099141/156891399-fbf01968-6643-41c8-a75b-1febde5c1127.png)

**Comment by TakosThings** [comment]
It's intended - as per the design documents:
![image](https://user-images.githubusercontent.com/20344790/156911774-a516bac8-162e-4d76-b21d-608ad636a814.png)

An option wouldn't be possible because of  how the buttons are structured. The Search 'button' for example is a [complete mess](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/main/toolbar/_search.scss).
