### ISSUE TITLE
Elements not themed when using other languages

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#71]
There are a few elements that are not themed when using other languages other than US English.
 - Home button
 - Better Discord Settings' icon is gone
 - Toolbar icons on the upper right side are back to the old

**Comment by TakosThings** [comment]
> Better Discord Settings' icon is gone

See #62. It's some odd inconsistency where `aria-controls` gets translated in some languages. I can only think of one way to 'fix' it but will break every time Discord moves an option in the menu, which it turns out is very often.

> Toolbar icons on the upper right side are back to the old

Also a translation thing, best that can be hoped for is that `data-list-item-id` tags are rolled out everywhere.
