### ISSUE TITLE
No Icon for Translate Message

### ISSUE THREAD

**Issue by Seath1337** [TakosThings/Fluent-Discord#98]
**Describe the bug**
Right clicking on the messages, the menu doesn't look nice at all with no icon for Translate Message and Add Reaction options. There's no icon for Translate Message and Add Reaction options. Can you fix this?

**Screenshots**
![Screenshot 2022-03-22 014603](https://user-images.githubusercontent.com/100544997/159416036-56be0950-aff8-4a14-86f6-96f3e248eee8.png)

**Comment by TakosThings** [comment]
Both of these are intentional.

Segoe Fluent Icons doesn't have a suitable icon to indicate 'translate', [so a blank one is used.](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/betterdiscord/plugins/_DevilBro.Translator.scss#L13-L18)

The Add Reaction sub menu doesn't have an icon so there aren't reuses or duplicates.
